pivot tables

In [2]:
import pandas as pd
import numpy as np
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    108     80   John  January      Q1
1  2023-01-02       B   West    188     12   Mary  January      Q1
2  2023-01-03       C  North    335     83    Bob  January      Q1
3  2023-01-04       D  South    192     51  Alice  January      Q1
4  2023-01-05       A   East    608     52   John  January      Q1
5  2023-01-06       B   West    198     29   Mary  January      Q1
6  2023-01-07       C  North    242     43    Bob  January      Q1
7  2023-01-08       D  South    894     74  Alice  January      Q1
8  2023-01-09       A   East    818     59   John  January      Q1
9  2023-01-10       B   West    870     19   Mary  January      Q1
10 2023-01-11       C  North    939     19    Bob  January      Q1
11 2023-01-12       D  South    298     17  Alice  January      Q1
12 2023-01-13       A   East    604     35   John  January      Q1
13 2023-01-14       B   West    609     52   Mary  January      Q1
14 2023-01-15       C  North    972     51    Bob  January      Q1
15 2023-01-16       D  South    914     89  Alice  January      Q1
16 2023-01-17       A   East    986     68   John  January      Q1
17 2023-01-18       B   West    918     13   Mary  January      Q1
18 2023-01-19       C  North    850     38    Bob  January      Q1
19 2023-01-20       D  South    999     22  Alice  January      Q1

In [3]:
pd.pivot_table(df, values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     624.8    NaN    NaN    NaN
North      NaN    NaN  667.6    NaN
South      NaN    NaN    NaN  659.4
West       NaN  556.6    NaN    NaN

In [6]:
pd.pivot_table(df, values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     608.0    NaN    NaN    NaN
North      NaN    NaN  850.0    NaN
South      NaN    NaN    NaN  894.0
West       NaN  609.0    NaN    NaN

In [9]:
#cross tabs
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [10]:
#cross tabs used for counting functions while pivot tables used for aggregate functions.